config/routes.rb
Rails.application.routes.draw do

  root 'users#index'

  resources :events, only: %i(index edit update)
  resources :groups
  resources :locations
  resources :users

  resources :posts do
    collection do
      get :write
      post :deliver
    end

  end
  resources :felicas, only: %i(index create show destroy) do
    resource :user, only: %i(new create edit update)
  end

  namespace :api do
    scope :arduino do
      resource :felica, only: [] do
        get :create
      end

      resource :event, only: [] do
        get :create
      end
    end
  end

  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end
end

app/models/group.rb
class Group < ActiveRecord::Base
  has_many :users
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :set_group, only: [:show, :edit, :update, :destroy]

  # GET /groups
  # GET /groups.json
  def index
    @groups = Group.all
  end

  # GET /groups/1
  # GET /groups/1.json
  def show
  end

  # GET /groups/new
  def new
    @group = Group.new
  end

  # GET /groups/1/edit
  def edit
  end

  # POST /groups
  # POST /groups.json
  def create
    @group = Group.new(group_params)

    respond_to do |format|
      if @group.save
        format.html { redirect_to groups_path, notice: 'Group was successfully created.' }
        format.json { render :show, status: :created, location: @group }
      else
        format.html { render :new }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /groups/1
  # PATCH/PUT /groups/1.json
  def update
    respond_to do |format|
      if @group.update(group_params)
        format.html { redirect_to @group, notice: 'Group was successfully updated.' }
        format.json { render :show, status: :ok, location: @group }
      else
        format.html { render :edit }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /groups/1
  # DELETE /groups/1.json
  def destroy
    @group.destroy
    respond_to do |format|
      format.html { redirect_to groups_url, notice: 'Group was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_group
      @group = Group.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def group_params
      params.require(:group).permit(:name)
    end
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/views/groups/_form.html.slim
= form_for @group do |f|
  - if @group.errors.any?
    #error_explanation
      h2 = "#{pluralize(@group.errors.count, "error")} prohibited this group from being saved:"
      ul
        - @group.errors.full_messages.each do |message|
          li = message

  .field.form-group
    = f.label :name
    = f.text_field :name, class: "form-control"
  .actions = f.submit '登録する', class: "btn btn-default"

app/views/groups/edit.html.slim
h1 グループの編集

== render 'form'

= link_to 'Show', @group
'|
= link_to 'Back', groups_path

app/views/groups/index.html.slim
h1 グループ一覧

table.table.table-striped
  thead
    tr
      th 名前
      th

  tbody
    - @groups.each do |group|
      tr
        td = group.name
        td = link_to '編集する', edit_group_path(group)

br

= link_to '新規グループ登録', new_group_path

app/views/groups/new.html.slim
h1 新規グループ

== render 'form'

= link_to '戻る', groups_path

app/views/groups/show.html.slim
p#notice = notice

p
  strong Name:
  = @group.name

= link_to 'Edit', edit_group_path(@group)
'|
= link_to 'Back', groups_path