config/routes.rb
Rails.application.routes.draw do

  root 'users#index'

  resources :events, only: %i(index edit update)
  resources :groups
  resources :locations
  resources :users

  resources :posts do
    collection do
      get :write
      post :deliver
    end

  end
  resources :felicas, only: %i(index create show destroy) do
    resource :user, only: %i(new create edit update)
  end

  namespace :api do
    scope :arduino do
      resource :felica, only: [] do
        get :create
      end

      resource :event, only: [] do
        get :create
      end
    end
  end

  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end
end

app/models/felica.rb
class Felica < ActiveRecord::Base
  validates :idm, presence: true, uniqueness: true

  scope :active, -> { where(activation: true) }
  scope :not_active, -> { where(activation: false) }

  has_one :user
  has_many :events

  def activate!
    return if activate?
    self.activation = true
    self.touch(:activated_at)
    save!
  end

  def activate?
    self.activation
  end

  def fetch_active_event
    event = self.events.last
    return nil if event.nil?
    return nil if event.close?

    event
  end
end

app/controllers/api/felicas_controller.rb
class Api::FelicasController < ApiController

  def create
    felica = Felica.where(idm: params[:idm]).first

    if felica.nil?
      felica = Felica.new(idm: params[:idm])
    end

    if felica.save
      render text: 200
    else
      render text: 401
    end
  end

end

app/controllers/felicas_controller.rb
class FelicasController < ApplicationController
  before_action :set_felica, only: [:show, :edit, :update, :destroy]

  # GET /felicas
  # GET /felicas.json
  def index
    @mode = params[:mode].presence || "all"
    @active = params[:activation]
    @felicas = case @mode
    when "all"
      Felica.all.page(params[:page])
    when "registered"
      Felica.active.page(params[:page])
    when "unregistered"
      Felica.not_active.page(params[:page])
    end
  end

  # GET /felicas/1
  # GET /felicas/1.json
  def show
  end

  # POST /felicas
  # POST /felicas.json
  def create
    @felica = Felica.new(felica_params)

    respond_to do |format|
      if @felica.save
        format.html { redirect_to @felica, notice: 'Felica was successfully created.' }
        format.json { render :show, status: :created, location: @felica }
      else
        format.html { render :new }
        format.json { render json: @felica.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /felicas/1
  # PATCH/PUT /felicas/1.json
  def update
    respond_to do |format|
      if @felica.update(felica_params)
        format.html { redirect_to @felica, notice: 'Felica was successfully updated.' }
        format.json { render :show, status: :ok, location: @felica }
      else
        format.html { render :edit }
        format.json { render json: @felica.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /felicas/1
  # DELETE /felicas/1.json
  def destroy
    @felica.destroy
    respond_to do |format|
      format.html { redirect_to felicas_url, notice: 'Felica was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_felica
      @felica = Felica.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def felica_params
      params.require(:felica).permit(:idm, :activation, :activated_at)
    end

  def search_params
    params.permit(:activation).select { |k, v| v.present? }
  end
end

app/helpers/felicas_helper.rb
module FelicasHelper
end

app/views/felicas/index.html.slim
h1 Felicaカード一覧

ul.nav.nav-pills
  li(class=("active" if @mode == "all") )
    = link_to felicas_path do
      span.badge.pull-right
        = Felica.count
      |すべてのカード一覧
  li(class=("active" if @mode == "unregistered") )
    = link_to felicas_path(mode: "unregistered") do
      span.badge.pull-right
        = Felica.not_active.count
      |ユーザ未登録のカード一覧
  li(class=("active" if @mode == "registered") )
    = link_to felicas_path(mode: "registered") do
      span.badge.pull-right
        = Felica.active.count
      | 登録済みのカード一覧


table.table.table-striped
  thead
    tr
      th id
      th カードID
      th アクティベーションした日
      th 操作
      th

  tbody
    - @felicas.each do |felica|
      tr
        td = felica.id
        td = felica.idm
        td = felica.activated_at
        td
          - if felica.activate?
            = link_to "ユーザの情報を更新する", edit_felica_user_path(felica)
          - else
            = link_to "ユーザと紐付ける", new_felica_user_path(felica)

app/views/felicas/show.html.slim
p#notice = notice

p
  strong Idm:
  = @felica.idm
p
  strong Activation:
  = @felica.activation
p
  strong Activated at:
  = @felica.activated_at

= link_to 'Back', felicas_path