config/routes.rb
Rails.application.routes.draw do

  root 'users#index'

  resources :events, only: %i(index edit update)
  resources :groups
  resources :locations
  resources :users

  resources :posts do
    collection do
      get :write
      post :deliver
    end

  end
  resources :felicas, only: %i(index create show destroy) do
    resource :user, only: %i(new create edit update)
  end

  namespace :api do
    scope :arduino do
      resource :felica, only: [] do
        get :create
      end

      resource :event, only: [] do
        get :create
      end
    end
  end

  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end
end

app/models/post.rb
class Post < ActiveRecord::Base
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :post, :update, :destroy]

  # GET /posts
  # GET /posts.json
  def index
    @groups = Group.all.map {|g| [g.name, g.id]}
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  def write
  end

  def deliver
    users = User.where(email: params[:post][:mail_addresses].split(","))
    users = users + User.where(group_id: params[:post][:group_ids])

    users.each do |user|
      UserMailer.notification(user: user, title: params[:post][:title], body: params[:post][:body]).deliver
    end
    redirect_to posts_path
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to posts_path, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to posts_path, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:template_name, :title, :body)
    end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form.html.slim
= form_for @post do |f|
  - if @post.errors.any?
    #error_explanation
      h2 = "#{pluralize(@post.errors.count, "error")} prohibited this post from being saved:"
      ul
        - @post.errors.full_messages.each do |message|
          li = message

  .field.form-group
    = f.label "テンプレート名"
    = f.text_field :template_name, class: "form-control"
  .field.form-group
    = f.label "タイトル"
    = f.text_field :title, class: "form-control"
  .field.form-group
    = f.label "本文"
    = f.text_area :body, class: "form-control", rows: 5
  .actions = f.submit '保存', class: "btn btn-default"

app/views/posts/_write_form.html.slim
= form_tag deliver_posts_path do
  .row
    .col-md-6
      .form.form-group
        = label :to, "To"
        = text_field :post, :mail_addresses, class: "form-control"
    .col-md-6
      .form.form-group
        = label :groups, "一斉送信"
        = select :post, :group_ids, @groups, {}, { class: "form-control", multiple: true }
  .form.form-group
    = label :title, "タイトル"
    = text_field :post, :title, class: "form-control"
  .form.form-group
    = label :body, "本文"
    = text_area :post, :body, class: "form-control", rows: 5

  = submit_tag "送信", class: "btn btn-default"

app/views/posts/edit.html.slim
h1 テンプレート編集

== render 'form'

= link_to 'Show', @post
'|
= link_to 'Back', posts_path

app/views/posts/index.html.slim
h1 メール送信

= render "write_form"

app/views/posts/new.html.slim
h1 新規メールテンプレート　

== render 'form'

= link_to 'Back', posts_path

app/views/posts/show.html.slim
p#notice = notice

p
  strong Template name:
  = @post.template_name
p
  strong Title:
  = @post.title
p
  strong Body:
  = @post.body

= link_to 'Edit', edit_post_path(@post)
'|
= link_to 'Back', posts_path

app/views/posts/write.html.slim
h1 メール送信

= render 'form'